name: test-actions-log-scroll-problem

on:
  push:
    branches:
      - 'main'

jobs:
  test-scroller-prob:
    runs-on: linux

steps:
  - name: run long job
    run: |
      for i in {1 .. 1000000}
      do
        echo i
      done
